baseURL                = "https://xiaxia.website/"
languageCode           = "zh-cn"
title                  = "夏小夏的博客"
defaultContentLanguage = "zh"
hasCJKLanguage         = true

[[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
